#!/usr/bin/env bash
# This script configures a new Ubuntu
# Installs Nginx web server, initial the root page, and
# permanently redirect the page redirect_me/

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html 
service nginx restart
LINE1="	server_name http://nyandi.tech;"
LINE2="	rewrite ^/redirect_me/$ http://nyandi.tech permanent;"
sed -i "s,^\sserver_name.*;,$LINE1\n$LINE2," /etc/nginx/sites-available/default
service nginx restart
