#!/usr/bin/env bash
# This script configures a new machine to have a custom 404 page

LINE1="error_page 404 /custom_404.html"
LINE2="location = /custom_404.html {"
LINE3="root /usr/share/nginx/html;"
LINE4="internal;"
LINE5="}"
echo "Ceci n'est pas une page" > "/usr/share/nginx/html/custom_404.html"
sed -i "/location.*{/i $LINE1\n$LINE2\n$LINE3\n$LINE4\n$LINE5" example
service nginx restart
