#!/usr/bin/env bash
# This script configures a new Ubuntu server
# Installs and configures Nginx web server
# Customizes the 404 page
apt-get -y update
apt-get install nginx
ufw allow 'Nginx HHTP'
LINE1=" error_page 404 /custom_404.html;"
LINE2=" location = /custom_404.html {"
LINE3=" root /usr/share/nginx/html;"
LINE4=" internal;"
sed "s,^\slocation.*{,$LINE1\n$LINE2\n$LINE3\n$LINE4," /etc/nginx/sites-available/default
service nginx restart
