#!/usr/bin/env bash
# Run NGINX as user 'nginx'
chown -R nginx:nginx /etc/nginx
chmod u+r /etc/nginx/nginx.conf
sed -i "/^\slisten.*/s/80/8080/" /etc/nginx/sites-available/default
pkill -9 apache2
service apache2 stop
sudo -u nginx service nginx restart
